### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by rebrec** [SNSA/agario-code#1]
Hello Thanks for this project to which i would love to participate
I am a bit new to JS and webdev but have a strong background in reversing (mainly Win32 but also a little web)
I just don't know how to use your tools, could you provide any url maybe in the Readme on how to use your tools ?

I guess i need to setup a webserver on localhost:8080, and the hook.js will do the mitm with the websocket but what to do with gulp ?

Sincerly

**Comment by rebrec** [comment]
I have done `npm install gulp-ruby-sass gulp-autoprefixer gulp-cssnano gulp-jshint gulp-concat gulp-uglify gulp-imagemin gulp-notify gulp-rename gulp-livereload gulp-cache del --save-dev
`
Then running with `gulp dev`

But when i go to http://localhost:8082 i am getting a blank page with lots of fail to log files (in my console) :

GET http://192.168.0.24:8082/css/master.css 
(index):81 GET http://192.168.0.24:8082/js/master.js 
(index):114 GET http://192.168.0.24:8082/js/a.js?a&ad_box_ net::ERR_BLOCKED_BY_CLIENT
(index):86 GET http://localhost:8080/hooks.js 
(index):82 GET http://192.168.0.24:8082/environment.js?v=676 
(index):83 GET http://192.168.0.24:8082/i18n.js?v=676 
(index):84 GET http://192.168.0.24:8082/main_out.js?v=676 
(index):85 GET http://192.168.0.24:8082/mc/agario.js?v=676 
(index):480 GET http://localhost:8080/agario.core.js 
(index):154 GET http://192.168.0.24:8082/mc/img/profilepic_guest.png 404 (Not Found)
(index):158 GET http://192.168.0.24:8082/mc/img/currency_icon.png 404 (Not Found)
(index):177 GET http://192.168.0.24:8082/img/login-perks.png 404 (Not Found)
(index):207 GET http://192.168.0.24:8082/mc/img/xpboost_3x_shop.png 404 (Not Found)
(index):212 GET http://192.168.0.24:8082/mc/img/massboost_3x_shop.png 404 (Not Found)
(index):432 GET http://192.168.0.24:8082/img/appstore.png 404 (Not Found)
(index):433 GET http://192.168.0.24:8082/img/google_play.png 404 (Not Found)
(index):487 Uncaught ReferenceError: $ is not defined(anonymous function) @ (index):487
(index):510 Uncaught ReferenceError: EnvConfig is not defined(anonymous function) @ (index):510
(index):520 Uncaught ReferenceError: $ is not defined


Am i doing something wrong ?

**Comment by heroandtn3** [comment]
Hello, I updated README file, let me know if you get it worked with the documentation I added.

**Comment by rebrec** [comment]
Thanks for your help
I followed the Modified README and everything is working now.

A few recommandations : on my computer the 8080 port was not available, the glup dev started an http server on port 8082, si i had to replace 3 times 8080 by 8082 in glupfile.js. 
Another error i made was to install the whole Next thing (even running glup dev...)

In fact, from what i have seen, installing tampermonkey or greasemonkey + going to one of the folowwing url is sufficient : 
- https://github.com/SNSA/NEXT/raw/master/userscripts/next.chrome.user.js

or

- https://github.com/SNSA/NEXT/raw/master/userscripts/next.firefox.user.js


Thanks again for your help and your nice hook

**P.S : is there a way to reach you (irc maybe ?) to talk about the new protocol modifications (like INIT2 changing a few times a day, the 255 opcode or the way to track down event.pushed inside agario.core.js)**

**Comment by heroandtn3** [comment]
Glad to see it works for you.

> In fact, from what i have seen, installing tampermonkey or greasemonkey + going to one of the folowwing url is sufficient

Definitely.

> is there a way to reach you (irc maybe ?)

I do not use irc. Maybe Skype? My Skype ID is heroandtn3
